"""
data/dotpe_products.py
=======================
DotPe's real product & price list, structured for the sales-recommendation
layer in ml/product_advisor.py.

Sourced from:
  - Products__1_.csv (the live price book — every ₹ figure below is copied
    from there, not invented)
  - Horizon_MS_Packages.pdf (Bronze/Silver/Gold/Platinum growth packages)
  - DotPe_CRM_Deck.pdf, DotPe_Amelo_Restaurant_AI.pptx, Waba_Brochure.pdf,
    DotPe_Deck_Updated_F&B.pdf (what each product actually does)

This file has no ML in it — it is a lookup table. The advisor picks from it
with deterministic rules; nothing here is generated by a language model.
"""

from __future__ import annotations

# ── Individual products / modules, with the price a sales rep would actually
# quote (the most common / entry SKU per family, from the price list) ─────────
# NOTE: Rista POS and Rista Reservation Module were deliberately dropped from
# this catalog (and from TAGS below) — sales asked to lead with Rista CRM only
# and stop surfacing the other standalone Rista modules as pitches.
PRODUCTS = {
    "rista_crm": {
        "name": "Rista Smart CRM",
        "platform": "Rista",
        "family": "Rista",
        "price": 24000, "unit": "per store / year",
        "what_it_is": ("RFM segmentation, loyalty programme, win-back and "
                        "feedback automation, 360° customer view."),
        "good_for": ["Casual Dining", "Fine Dining", "PBCL", "Cafe"],
    },
    "sova": {
        "name": "SOVA (Agentic AI Order Taker)",
        "platform": "Rista / Dot Commerce bundle",
        "family": "SOVA",
        "price": 24000, "unit": "per store / year (Rista Standard QR + SOVA bundle)",
        "what_it_is": ("Conversational AI host for table-side and phone "
                        "ordering — takes phone-in orders, handles table "
                        "requests, answers menu questions, and upsells "
                        "without needing extra front-of-house staff."),
        "good_for": ["Fine Dining", "PBCL"],
    },
    "amello": {
        "name": "DotPe Amelo",
        "platform": "Amello",
        "family": "Amello",
        "price": 60000, "unit": "per store / year (or ₹5,000/month)",
        "what_it_is": ("AI restaurant-growth platform — sales intelligence, "
                        "customer segmentation, marketing automation, menu "
                        "performance, competitor benchmarking, sentiment "
                        "analysis, an AI chat assistant and revenue forecasting."),
        "good_for": ["Casual Dining", "Fine Dining", "Cloud Kitchen", "QSR", "PBCL", "Cafe"],
    },
    "qr_ordering": {
        "name": "QR Ordering Unified (Multi-Payment)",
        "platform": "Dot Commerce",
        "family": "QR Ordering",
        "price": 7000, "unit": "per store per brand / year",
        "what_it_is": ("Own-branded ordering site + QR menu, discoverable via "
                        "Google, Instagram, Facebook and WhatsApp; bank-offer "
                        "and upsell engine built in."),
        "good_for": ["QSR", "Cafe", "Cloud Kitchen", "Casual Dining"],
    },
    "waba_sme": {
        "name": "WhatsApp SME (Annual)",
        "platform": "WABA",
        "family": "WhatsApp (WABA)",
        "price": 20000, "unit": "per brand / year",
        "what_it_is": ("Verified WhatsApp Business handle — campaigns, real-time "
                        "order updates, automated re-engagement and feedback flows."),
        "good_for": ["QSR", "Cafe", "Casual Dining", "Cloud Kitchen"],
    },
    "waba_enterprise": {
        "name": "WhatsApp Enterprise (Annual)",
        "platform": "WABA",
        "family": "WhatsApp (WABA)",
        "price": 50000, "unit": "per brand / year",
        "what_it_is": "Enterprise-tier WhatsApp marketing for multi-outlet brands.",
        "good_for": ["Casual Dining", "Fine Dining", "PBCL"],
    },
    "horizon_consulting": {
        "name": "DotPe Horizon (Brand Consulting)",
        "platform": "Rista / Horizon",
        "family": "Horizon",
        "price": 10000, "unit": "per brand, one-time",
        "what_it_is": "One-time growth/brand consulting engagement.",
        "good_for": ["Fine Dining", "Casual Dining", "PBCL"],
    },
    "bundle_pos_sova_amello_crm": {
        "name": "Bundle: Rista QR Ordering + SOVA + Amello + CRM",
        "platform": "Rista",
        "family": "Bundle",
        "price": 60000, "unit": "per store / year",
        "what_it_is": "The full-stack bundle — POS, AI ordering, AI growth intelligence and CRM together.",
        "good_for": ["Casual Dining", "Cloud Kitchen", "QSR"],
    },
}

# ── Short, sales-ready pitch reason per PRODUCT FAMILY (the top-level product
# a rep actually leads with — Rista / SOVA / Amello / QR Ordering / WABA /
# Horizon — as opposed to the specific SKU under it, e.g. "Rista Reservation
# Module" is a Rista sub-product, not a separate thing to pitch) ────────────
FAMILY_REASONS = {
    "Rista":            "CRM, loyalty and win-back automation — the customer-data layer to keep the surge from being a one-off.",
    "SOVA":              "AI-powered table-side and phone ordering — handles reservation calls, phone-in orders and table requests without adding front-of-house headcount.",
    "Amello":            "AI growth layer — segmentation and campaigns to convert a demand spike into repeat, loyal customers.",
    "QR Ordering":       "Owned, commission-free ordering channel to capture delivery demand directly instead of losing margin to aggregators.",
    "WhatsApp (WABA)":   "Direct-to-customer channel for win-back and re-engagement — the right lever when demand is soft, not surging.",
    "Horizon":           "Managed always-on growth retainer for brands that want this handled rather than run in-house.",
    "Bundle":            "The full-stack sale — POS, AI ordering, AI growth intelligence and CRM in one package. Lead with this when demand is already surging and the outlet is ready to commit across the board, instead of pitching each piece separately.",
}

# ── Horizon managed-growth retainers (Horizon_MS_Packages.pdf) ────────────────
HORIZON_PACKAGES = {
    "Bronze":   {"retainer": 30000, "outlets_included": 1, "unit": "per month",
                 "pitch": "1-2 ads/month, basic segmentation, monthly reporting — entry point for a single-outlet brand testing managed marketing."},
    "Silver":   {"retainer": 50000, "outlets_included": 3, "unit": "per month",
                 "pitch": "retargeting, lifecycle CRM cohorts, fortnightly optimisation — for a brand with 3+ outlets ready for always-on campaigns."},
    "Gold":     {"retainer": 75000, "outlets_included": 5, "unit": "per month",
                 "pitch": "full CRM automation, managed sponsored-listing optimisation, weekly real-time reviews, price-elasticity menu work — for multi-outlet brands defending or growing share aggressively."},
    "Platinum": {"retainer": None, "outlets_included": "all", "unit": "custom",
                 "pitch": "fully customised scope/team/pricing, dedicated senior AM and growth strategist — for enterprise chains."},
}

# ── Deterministic tag → product mapping used by the advisor ──────────────────
# "surge" = push for more volume/AOV during a demand spike
# "defend" = retention play to offset a soft period
# Kept deliberately short (max 2 per tag) — sales asked for only the relevant
# products, not the full catalog every time. When demand is rising for a
# delivery-led format, lead with the full-stack BUNDLE rather than listing
# each of its components as separate line items.
TAGS = {
    "surge_delivery":     ["bundle_pos_sova_amello_crm", "qr_ordering"],
    "surge_dine_in":      ["rista_crm", "amello"],
    "surge_fine_dining":  ["sova", "rista_crm"],
    "surge_bar":          ["sova", "waba_enterprise"],
    "defend_retention":   ["rista_crm", "waba_sme"],
    "always_on_growth":   ["amello", "horizon_consulting"],
}


# Soft-demand variant of the family pitch, for families whose main
# FAMILY_REASONS copy talks about a "surge"/"spike" — which reads oddly
# stitched behind a "demand is dropping" driver clause.
FAMILY_REASONS_SOFT = {
    "Rista":  "Core POS, CRM and table-booking data — use it to win back bookings and visits through this soft patch.",
    "Amello": "AI growth layer — segmentation and win-back campaigns to rebuild demand through this soft patch.",
    "Horizon": "Managed always-on growth retainer to help rebuild demand once this soft patch passes.",
}


def contextual_pitch(family: str, pct: float | None = None,
                     event_names: list[str] | None = None,
                     weather_note: str | None = None) -> str:
    """Build the 'why pitch this' line so it names the actual driver — which
    festival/event, how big the demand swing is, and notable weather — rather
    than a static, always-the-same description of the product. The product's
    core capability (FAMILY_REASONS) is still the payoff clause; the context
    in front of it is what changes call to call."""
    is_down = pct is not None and pct < 0
    core = (FAMILY_REASONS_SOFT.get(family) if is_down else None) or FAMILY_REASONS.get(family, "")

    if pct is None:
        mag = None
    elif pct >= 40:  mag = f"a sharp {pct:.0f}% surge"
    elif pct >= 20:  mag = f"a strong {pct:.0f}% lift"
    elif pct >= 8:   mag = f"a {pct:.0f}% lift"
    elif pct >= 3:   mag = f"a modest {pct:.0f}% uptick"
    elif pct <= -30: mag = f"a sharp {abs(pct):.0f}% drop"
    elif pct <= -15: mag = f"a {abs(pct):.0f}% dip"
    elif pct <= -5:  mag = f"a soft {abs(pct):.0f}% dip"
    else:            mag = "roughly normal demand"

    if event_names:
        names = event_names[:2]
        ev_txt = " and ".join(names)
        verb = "are" if len(names) > 1 else "is"
        driver = f"{ev_txt} {verb} driving {mag} here" if mag else f"{ev_txt} {verb} active here"
    elif mag:
        driver = f"Forecast demand here is showing {mag}"
    else:
        driver = ""

    parts = [p for p in [driver, weather_note] if p]
    context = (" — ".join(parts) + ". ") if parts else ""
    return f"{context}{core}"


def all_products() -> dict:
    return PRODUCTS


def horizon_tier_for(signal: str) -> tuple[str, dict]:
    """Pick a Horizon retainer tier by demand posture — growth signals get the
    heavier managed tier, soft signals get the lighter one so cost matches
    what the outlet can justify right now."""
    if signal in ("very_high_up", "high_up"):
        tier = "Gold"
    elif signal in ("slight_up", "neutral"):
        tier = "Silver"
    else:
        tier = "Bronze"
    return tier, HORIZON_PACKAGES[tier]
