"""
Ask Dotpool — conversational access to the forecasting model.
pages/02_Ask_DotPool.py

The assistant answers by CALLING the trained model, never by guessing. Every
number in a reply came out of a tool call you can inspect under "sources".
"""

import os
import sys
from datetime import date

import streamlit as st

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from ml.chat_agent import answer                     # noqa: E402
from ml.llm import LLMUnavailable                    # noqa: E402
from components.llm_sidebar import llm_sidebar           # noqa: E402
from components.branding import page_icon, inject_theme, sidebar_header, page_logo, RED

st.set_page_config(page_title="Ask DotPool", page_icon=page_icon(), layout="wide")
inject_theme()
page_logo()

st.markdown(f"""
<style>
.hero{{background:linear-gradient(135deg,#1a1a1a 0%,#000000 100%);
  border:1px solid rgba(255,255,255,.08);border-radius:14px;
  padding:22px 26px;color:white;margin-bottom:18px;border-left:4px solid {RED}}}
.hero h1{{margin:0;font-size:26px;font-weight:700}}
.hero p{{margin:6px 0 0;opacity:.65;font-size:16px}}
.srcbox{{background:rgba(0,0,0,.04);border-left:3px solid {RED};border-radius:8px;
  padding:8px 12px;margin:4px 0;color:rgba(0,0,0,.75);font-size:15px;font-family:monospace}}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="hero">
  <h1>Ask DotPool</h1>
  <p>Ask in plain language, for the DotPe Sales team. Answers are generated by calling
     the trained forecasting model plus the DotPe product/price book — the assistant
     is not allowed to invent numbers or products.</p>
</div>
""", unsafe_allow_html=True)

llm = llm_sidebar()

sidebar_header("Ask DotPool")
with st.sidebar:
    st.markdown("### What it can answer")
    st.caption(
        "— demand for a city / date / restaurant format\n\n"
        "— a week or month ahead\n\n"
        "— which events are driving a spike\n\n"
        "— what to pitch, and to which restaurant type — SOVA, Amello, Rista CRM, "
        "WABA, Horizon retainers — with real DotPe prices\n\n"
        "— broader sales-strategy questions: objection handling, account "
        "sequencing, city prioritisation, renewal framing\n\n"
        "— how accurate the model is\n\n"
        "It reasons by restaurant format (QSR, Fine Dining, PBCL, Casual Dining, "
        "Cloud Kitchen, Cafe), not by individual outlet — it cannot see any one "
        "merchant's own sales, menu or competitors unless you attach that "
        "document or screenshot yourself.")
    if st.button("Clear conversation", use_container_width=True):
        st.session_state.pop("chat", None)
        st.session_state.pop("history", None)
        st.session_state.pop("attachments", None)
        st.rerun()

if not llm["available"]:
    st.warning(
        "**No language model connected yet.** The forecasting model works fine "
        "without one — only this chat layer needs it. Two options:\n\n"
        "**Ollama** — free, runs on your machine, no API key: install from "
        "[ollama.com](https://ollama.com/download), then `ollama pull qwen2.5:7b` "
        "and `ollama serve`.\n\n"
        "**GPT-4** — set `OPENAI_API_KEY` and `DOTPOOL_LLM_MODEL=gpt-4o`.\n\n"
        "Setup commands are in the sidebar. Meanwhile, the Restaurant Impact page "
        "gives you the same forecasts without the conversation.")

SUGGESTIONS = [
    "What should we pitch to cloud kitchens in Bengaluru for Diwali week?",
    "Which DotPe product fits PBCL outlets in Mumbai next weekend, and why?",
    "Which restaurant format in Pune has the strongest pricing opportunity next month?",
    "Demand is soft in Delhi in early October — what's the retention pitch for QSR?",
]

if "chat" not in st.session_state:
    st.session_state.chat = []
    st.session_state.history = []
if "pending_files" not in st.session_state:
    st.session_state.pending_files = []

if not st.session_state.chat:
    st.markdown("**Try one of these:**")
    cols = st.columns(2)
    for i, s in enumerate(SUGGESTIONS):
        if cols[i % 2].button(s, key=f"sug{i}", use_container_width=True):
            st.session_state.pending = s
            st.rerun()

for msg in st.session_state.chat:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("files"):
            st.caption("Attached: " + ", ".join(msg["files"]))
        if msg.get("trace"):
            with st.expander(f"Sources — {len(msg['trace'])} model call(s)"):
                for t in msg["trace"]:
                    err = f"  [error] {t['error']}" if t.get("error") else ""
                    st.markdown(
                        f"<div class='srcbox'>{t['tool']}({t['input']}){err}</div>",
                        unsafe_allow_html=True)

with st.expander("Attach files or images", expanded=False):
    uploaded = st.file_uploader(
        "Add context for this question — a menu, a screenshot, a spreadsheet, a transcript",
        type=["txt", "md", "csv", "json", "png", "jpg", "jpeg"],
        accept_multiple_files=True, key="uploader")
    if uploaded:
        st.session_state.pending_files = uploaded
        st.caption(f"{len(uploaded)} file(s) ready — they'll attach to your next message.")

prompt = st.chat_input("Ask about demand…") or st.session_state.pop("pending", None)

if prompt:
    files = st.session_state.pop("pending_files", []) or []
    attachments, file_names = [], []
    for f in files:
        file_names.append(f.name)
        raw = f.getvalue()
        ext = f.name.rsplit(".", 1)[-1].lower()
        if ext in ("png", "jpg", "jpeg"):
            import base64
            media = "image/png" if ext == "png" else "image/jpeg"
            attachments.append({"kind": "image", "name": f.name, "media_type": media,
                                "data": base64.b64encode(raw).decode()})
        else:
            try:
                text = raw.decode("utf-8", errors="replace")[:8000]
            except Exception:
                text = ""
            attachments.append({"kind": "text", "name": f.name, "text": text})

    st.session_state.chat.append({"role": "user", "content": prompt, "files": file_names})
    with st.chat_message("user"):
        st.markdown(prompt)
        if file_names:
            st.caption("Attached: " + ", ".join(file_names))
    with st.chat_message("assistant"):
        if not llm["available"]:
            msg = ("I can't answer yet — no language model is connected. "
                   "Run Ollama locally (free, no key) or set an OpenAI/Anthropic key; "
                   "the sidebar has the exact commands. The forecasts themselves are "
                   "unaffected — the Restaurant Impact page still works.")
            st.warning(msg)
            st.session_state.chat.append({"role": "assistant", "content": msg})
        else:
            with st.spinner("Consulting the forecast model…"):
                try:
                    res = answer(prompt, history=st.session_state.history, attachments=attachments)
                    st.markdown(res["text"])
                    st.session_state.history = res["messages"] + [
                        {"role": "assistant", "content": res["text"]}]
                    st.session_state.chat.append(
                        {"role": "assistant", "content": res["text"],
                         "trace": res["tool_trace"]})
                    if res["tool_trace"]:
                        with st.expander(f"Sources — {len(res['tool_trace'])} model call(s)"):
                            for t in res["tool_trace"]:
                                err = f"  [error] {t['error']}" if t.get("error") else ""
                                st.markdown(
                                    f"<div class='srcbox'>{t['tool']}({t['input']}){err}</div>",
                                    unsafe_allow_html=True)
                except LLMUnavailable as exc:
                    st.error(str(exc))
                except Exception as exc:                          # noqa: BLE001
                    st.error(f"Something went wrong: {exc}")

st.caption(f"Model-backed answers · {date.today().isoformat()} · "
           "figures come from the LightGBM forecaster, not the language model.")
